from dal import autocomplete

from . import models
from django import forms
import django_filters
from .models import *
from datetime import date


class DateInput(forms.DateInput):
    input_type = 'date'


class PresupuestoEventoForm(forms.ModelForm):
    # estado=
    class Meta:
        model = PresupuestoEvento

        fields = "__all__"
        labels = {
            'estado': '',
            'codigo': '',
            'fecha': '',
            'motivo_anular':'Motivo de anulación',
            'ingreso_individual_sin_desc': '',
            'ingreso_total_sin_desc': '',
            'descuento_maximo': '',
            'descuento_individual': '',
            'descuento_total': '',

            'ingreso_neto_individual': '',
            'ingreso_neto_total': '',

            'porcentaje_honorario_instructor': '',
            'honorario_total_evento': '',

            'impuesto_select': '',
            'impuesto_unitario': '',
            'impuesto_total': '',

            'pasaje_instructor': '',
            'pasaje_instructor_unitario': '',
            'pasaje_instructor_total': '',

            'hospedaje_alimentacion_instructor': '',
            'hospedaje_alimentacion_instructor_dias': '',
            'hospedaje_alimentacion_instructor_n': '',
            'hospedaje_alimentacion_instructor_unitario': '',
            'hospedaje_alimentacion_instructor_total': '',

            'break_instructor': '',
            'break_instructor_dias': '',
            'break_instructor_n': '',
            'break_instructor_unitario': '',
            'break_instructor_total': '',

            'almuerzo_instructor': '',
            'almuerzo_instructor_dias': '',
            'almuerzo_instructor_n': '',
            'almuerzo_instructor_unitario': '',
            'almuerzo_instructor_total': '',

            'pasaje_personal': '',
            'pasaje_personal_dias': '',
            'pasaje_personal_unitario': '',
            'pasaje_personal_total': '',

            'hospedaje_alimentacion_personal': '',
            'hospedaje_alimentacion_personal_dias': '',
            'hospedaje_alimentacion_personal_unitario': '',
            'hospedaje_alimentacion_personal_total': '',

            'movilizacion_personal_dias': '',
            'movilizacion_personal_unitario': '',
            'movilizacion_personal_total': '',

            'instalaciones': '',
            'instalaciones_unitario': '',
            'instalaciones_total': '',

            'publicidad_unitario': '',
            'publicidad_total': '',

            'personal_evento_unitario': '',
            'personal_evento_total': '',

            'prospecto_evento': '',
            'prospecto_evento_unitario': '',
            'prospecto_evento_total': '',

            'total_egresos_fijos': '',

            # Material del evento
            'certificados': '',
            'certificados_unitario': '',
            'certificados_total': '',

            'carpeta': '',
            'carpeta_unitario': '',
            'carpeta_total': '',

            'maletin': '',
            'maletin_unitario': '',
            'maletin_total': '',

            'block': '',
            'block_unitario': '',
            'block_total': '',

            'lapiz': '',
            'lapiz_unitario': '',
            'lapiz_total': '',

            'pluma': '',
            'pluma_unitario': '',
            'pluma_total': '',

            'credencial_plastico': '',
            'credencial_plastico_unitario': '',
            'credencial_plastico_total': '',

            'credencial_pvc': '',
            'credencial_pvc_unitario': '',
            'credencial_pvc_total': '',

            'pendrive': '',
            'pendrive_unitario': '',
            'pendrive_total': '',

            'otros_materiales': '',
            'otros_materiales_unitario': '',
            'otros_materiales_total': '',

            'break_evento': '',
            'break_evento_dias': '',
            'break_evento_unitario': '',
            'break_evento_total': '',

            'almuerzo_evento': '',
            'almuerzo_evento_dias': '',
            'almuerzo_evento_unitario': '',
            'almuerzo_evento_total': '',

            'ceremonia': '',
            'ceremonia_unitario': '',
            'ceremonia_total': '',

            'aportacion_espol_porcentaje': '',
            'aportacion_espol_unitario': '',
            'aportacion_espol_total': '',

            'aportacion_espoltech_porcentaje': '',
            'aportacion_espoltech_unitario': '',
            'aportacion_espoltech_total': '',

            'aportacion_ministerio_porcentaje': '',
            'aportacion_ministerio_unitario': '',
            'aportacion_ministerio_total': '',

            'aportacion_facultad': '',
            'aportacion_facultad_porcentaje_unitario': '',
            'aportacion_facultad_unitario': '',
            'aportacion_facultad_total': '',

            'movilizacion_interna_unitario': '',
            'movilizacion_interna_total': '',

            'cafeteria_limpieza': '',
            'cafeteria_limpieza_unitario': '',
            'cafeteria_limpieza_total': '',

            'imprevisto_porcentaje': '',
            'imprevisto_unitario': '',
            'imprevisto_total': '',

            'total_egresos_variables': '',
            'total_egresos': '',

            'egreso_variable_unit': '',
            'utilidad': '',
            'margen_contribucion': '',
            'punto_equilibrio': '',

            'n_cursos': '',
            'participacion_total': '',

            'pago_docente_total': '',
        }
        widgets = {
            'empresa': forms.Select(attrs={'class': 'form-control select2'}),
            'centro_costos': forms.Select(attrs={'onchange': 'CargarAportacion("centro_costo",this.value)'}),
            'fecha': forms.DateInput(attrs={'type': 'date', 'value': date.today, 'readonly': True, 'class': 'form-control'}),
            "pasaje_instructor": forms.Select(attrs={'onchange': 'CargarInfo("pasaje_instructor",this.value);', 'class': 'form-control'}),
            "estado": forms.TextInput(attrs={'class': 'form-control', 'readonly': True, 'placeholder': 'Estado'}),
            "codigo": forms.TextInput(attrs={'class': 'form-control', 'readonly': True, 'placeholder': 'Código'}),
            "costo_hora_instructores": forms.HiddenInput(),
            "costo_instructores": forms.TextInput(attrs={'readonly': True, 'class': 'text-currency textInput form-control'}),
            "hora_inicio": forms.TimeInput(attrs={'type': 'time'}),
            "hora_fin": forms.TimeInput(attrs={'type': 'time'}),
            "n_horas": forms.NumberInput(attrs={'min': 0}),
            "n_dias": forms.NumberInput(attrs={'min': 0}),
            "n_participantes": forms.NumberInput(attrs={'min': 0}),
            'ingreso_individual_sin_desc': forms.NumberInput(attrs={'placeholder': "Ingreso sin descuento individual", 'class': 'text-currency textInput form-control'}),
            'descuento_maximo': forms.NumberInput(attrs={'placeholder': "Descuento máximo", 'step': 1, 'class': 'text-currency textInput form-control'}),
            'descuento_individual': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Descuento individual", 'class': 'text-currency textInput form-control'}),
            "ingreso_total_sin_desc": forms.NumberInput(attrs={'readonly': True, 'placeholder': "Ingreso sin descuento total", 'class': 'text-currency textInput form-control'}),
            "descuento_total": forms.NumberInput(attrs={'readonly': True, 'placeholder': "Descuento max total", 'class': 'text-currency textInput form-control'}),
            'ingreso_neto_individual': forms.NumberInput(attrs={'readonly': True, 'class': 'border border-success text-currency textInput form-control', 'placeholder': "Ingreso neto individual"}),
            'ingreso_neto_total': forms.NumberInput(attrs={'readonly': True, 'class': 'border border-success text-currency textInput form-control', 'placeholder': "Ingreso neto total"}),
            'porcentaje_honorario_instructor': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Honorario', 'class': 'text-currency textInput form-control'}),
            'honorario_total_evento': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Honorario total del evento", 'class': 'egreso-fijo text-currency textInput form-control'}),

            'impuesto_unitario': forms.HiddenInput(),
            'impuesto_total': forms.HiddenInput(),
            'impuesto_select': forms.HiddenInput(),

            'pasaje_instructor_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                   'placeholder': "Costo Pasaje",
                                                                   'class': 'text-currency textInput form-control valor-total',
                                                                   'data-total': 'id_pasaje_instructor_total',
                                                                   'data-depend': 'False',
                                                                   'data-field': ''}),
            'pasaje_instructor_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Pasaje Total", 'class': 'egreso-fijo text-currency textInput form-control'}),
            "hospedaje_alimentacion_instructor": forms.Select(attrs={'onchange': 'CargarInfo("hospedaje_alimentacion_instructor",this.value);', 'class': 'form-control'}),
            'hospedaje_alimentacion_instructor_n': forms.NumberInput(attrs={'min': 0,
                                                                            'placeholder': '# instructores',
                                                                            'class': 'textInput form-control valor-total',
                                                                            "data-total": "hospedaje_alimentacion_instructor_r",
                                                                            'data-depend': 'True',
                                                                            'data-field': 'id_hospedaje_alimentacion_instructor_dias'}),
            'hospedaje_alimentacion_instructor_dias': forms.NumberInput(attrs={'min': 0,
                                                                               'placeholder': "# días",
                                                                               'class': 'textInput form-control valor-total',
                                                                               'data-total': 'hospedaje_alimentacion_instructor_r',
                                                                               'data-depend': 'True',
                                                                               'data-field': 'id_hospedaje_alimentacion_instructor_n'}),
            'hospedaje_alimentacion_instructor_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                                   'placeholder': "Costo HyA por día",
                                                                                   'class': 'text-currency textInput form-control valor-total',
                                                                                   'data-total': 'id_hospedaje_alimentacion_instructor_total',
                                                                                   'data-depend': 'True',
                                                                                   'data-field': 'hospedaje_alimentacion_instructor_r'}),
            'hospedaje_alimentacion_instructor_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo HyA Total", 'class': 'egreso-fijo text-currency textInput form-control'}),
            "break_instructor": forms.Select(attrs={'onchange': 'CargarInfo("break_instructor",this.value);', 'class': 'form-control'}),
            'break_instructor_n': forms.NumberInput(attrs={'min': 0,
                                                           'placeholder': '# instructores',
                                                           'class': 'textInput form-control valor-total',
                                                           "data-total": "break_instructor_r",
                                                           'data-depend': 'True',
                                                           'data-field': 'id_break_instructor_dias'}),
            'break_instructor_dias': forms.NumberInput(attrs={'min': 0,
                                                              'placeholder': "# días",
                                                              'class': 'textInput form-control valor-total',
                                                              'data-total': 'break_instructor_r',
                                                              'data-depend': 'True',
                                                              'data-field': 'id_break_instructor_n'}),
            'break_instructor_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                  'placeholder': "Costo Break por día",
                                                                  'class': 'text-currency textInput form-control valor-total',
                                                                  'data-total': 'id_break_instructor_total',
                                                                  'data-depend': 'True',
                                                                  'data-field': 'break_instructor_r'}),
            'break_instructor_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Break Total", 'class': 'egreso-fijo text-currency textInput form-control'}),
            "almuerzo_instructor": forms.Select(attrs={'onchange': 'CargarInfo("almuerzo_instructor",this.value);', 'class': 'form-control'}),
            'almuerzo_instructor_n': forms.NumberInput(attrs={'min': 0,
                                                              'placeholder': '# instructores',
                                                              'class': 'textInput form-control valor-total',
                                                              "data-total": "almuerzo_instructor_r",
                                                              'data-depend': 'True',
                                                              'data-field': 'id_almuerzo_instructor_dias'}),
            'almuerzo_instructor_dias': forms.NumberInput(attrs={'min': 0,
                                                                 'placeholder': "# días",
                                                                 'class': 'textInput form-control valor-total',
                                                                 "data-total": "almuerzo_instructor_r",
                                                                 'data-depend': 'True',
                                                                 'data-field': 'id_almuerzo_instructor_n'}),
            'almuerzo_instructor_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                     'placeholder': "Costo Almuerzo por día",
                                                                     'class': 'text-currency textInput form-control valor-total',
                                                                     "data-total": "id_almuerzo_instructor_total",
                                                                     'data-depend': 'True',
                                                                     'data-field': 'almuerzo_instructor_r'}),
            'almuerzo_instructor_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Almuerzo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            "pasaje_personal": forms.Select(attrs={'onchange': 'CargarInfo("pasaje_personal",this.value);', 'class': 'form-control'}),
            'pasaje_personal_dias': forms.NumberInput(attrs={'min': 0,
                                                             'placeholder': "# días",
                                                             'class': 'textInput form-control valor-total',
                                                             'data-total': 'id_pasaje_personal_total',
                                                             'data-depend': 'True',
                                                             'data-field': 'id_pasaje_personal_unitario'}),
            'pasaje_personal_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                 'placeholder': "Costo HyA por día",
                                                                 'class': 'text-currency textInput form-control valor-total',
                                                                 'data-total': 'id_pasaje_personal_total',
                                                                 'data-depend': 'True',
                                                                 'data-field': 'id_pasaje_personal_dias'}),
            'pasaje_personal_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo HyA Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            "hospedaje_alimentacion_personal": forms.Select(attrs={'onchange': 'CargarInfo("hospedaje_alimentacion_personal",this.value);', 'class': 'form-control'}),
            'hospedaje_alimentacion_personal_dias': forms.NumberInput(attrs={'min': 0,
                                                                             'placeholder': "# días",
                                                                             'class': 'textInput form-control valor-total',
                                                                             'data-total': 'id_hospedaje_alimentacion_personal_total',
                                                                             'data-depend': 'True',
                                                                             'data-field': 'id_hospedaje_alimentacion_personal_unitario'
                                                                             }),
            'hospedaje_alimentacion_personal_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                                 'placeholder': "Costo HyA por día",
                                                                                 'class': 'text-currency textInput form-control valor-total',
                                                                                 'data-total': 'id_hospedaje_alimentacion_personal_total',
                                                                                 'data-depend': 'True',
                                                                                 'data-field': 'id_hospedaje_alimentacion_personal_dias'
                                                                                 }),
            'hospedaje_alimentacion_personal_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo HyA Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            'movilizacion_personal_dias': forms.NumberInput(attrs={'min': 0,
                                                                   'placeholder': "# días",
                                                                   'class': 'textInput form-control valor-total',
                                                                   'data-total': 'id_movilizacion_personal_total',
                                                                   'data-depend': 'True',
                                                                   'data-field': 'id_movilizacion_personal_unitario'}),
            'movilizacion_personal_unitario': forms.NumberInput(attrs={'placeholder': "Costo HyA por día",
                                                                       'class': 'text-currency textInput form-control valor-total',
                                                                       'data-total': 'id_movilizacion_personal_total',
                                                                       'data-depend': 'True',
                                                                       'data-field': 'id_movilizacion_personal_dias'}),
            'movilizacion_personal_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo HyA Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            "instalaciones": forms.Select(attrs={'onchange': 'CargarInfo("instalaciones",this.value);', 'class': 'form-control'}),
            'instalaciones_unitario': forms.NumberInput(attrs={'readonly': True,
                                                               'placeholder': "Costo por día",
                                                               'class': 'text-currency textInput form-control valor-total',
                                                               'data-total': 'id_instalaciones_total',
                                                               'data-depend': 'True',
                                                               'data-field': 'id_n_horas'
                                                               }),
            'instalaciones_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            'publicidad_unitario': forms.NumberInput(attrs={'placeholder': "Costo por día",
                                                            'class': 'text-currency textInput form-control valor-total',
                                                            'data-total': 'id_publicidad_total',
                                                            'data-depend': 'False',
                                                            'data-field': ''
                                                            }),
            'publicidad_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            'publicidad_evento_unitario': forms.NumberInput(attrs={'placeholder': "Costo por día",
                                                                   'class': 'text-currency textInput form-control valor-total',
                                                                   'data-total': 'id_publicidad_evento_total',
                                                                   'data-depend': 'True',
                                                                   'data-field': 'id_n_participantes'
                                                                   }),
            'publicidad_evento_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            'personal_evento_unitario': forms.NumberInput(attrs={'placeholder': "Costo por día",
                                                                 'class': 'text-currency textInput form-control valor-total',
                                                                 'data-total': 'id_personal_evento_total',
                                                                 'data-depend': 'True',
                                                                 'data-field': 'id_n_horas'
                                                                 }),
            'personal_evento_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            "prospecto_evento": forms.Select(attrs={'onchange': 'CargarInfo("prospecto_evento",this.value);', 'class': 'form-control'}),
            'prospecto_evento_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                  'placeholder': "Costo por día",
                                                                  'class': 'text-currency textInput form-control valor-total',
                                                                  'data-total': 'id_prospecto_evento_total',
                                                                  'data-depend': 'False',
                                                                  'data-field': ''
                                                                  }),
            'prospecto_evento_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),
            'total_egresos_fijos': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Total egresos fijos', 'class': 'punto form-control textInput text-currency border border-success'}),

            'certificados': forms.Select(attrs={'onchange': 'CargarInfo("certificados",this.value);', 'class': 'form-control', 'data-label': 'id_certificados_unitario'}),
            'certificados_unitario': forms.NumberInput(attrs={'readonly': True,
                                                              'placeholder': "Costo unitario",
                                                              'class': 'text-currency textInput form-control valor-total',
                                                              'data-total': 'id_certificados_total',
                                                              'data-depend': 'True',
                                                              'data-field': 'id_n_participantes'}),
            'certificados_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'carpeta': forms.Select(attrs={'onchange': 'CargarInfo("carpeta",this.value);', 'class': 'form-control', 'data-label': 'id_carpeta_unitario'}),
            'carpeta_unitario': forms.NumberInput(attrs={'readonly': True,
                                                         'placeholder': "Costo unitario",
                                                         'class': 'text-currency textInput form-control valor-total',
                                                         'data-total': 'id_carpeta_total',
                                                         'data-depend': 'True',
                                                         'data-field': 'id_n_participantes'}),
            'carpeta_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'maletin': forms.Select(attrs={'onchange': 'CargarInfo("maletin",this.value);', 'class': 'form-control otros', 'data-label': 'id_maletin_unitario'}),
            'maletin_unitario':  forms.NumberInput(attrs={'readonly': True,
                                                          'placeholder': "Costo unitario",
                                                          'class': 'text-currency textInput form-control valor-total',
                                                          'data-total': 'id_maletin_total',
                                                          'data-depend': 'True',
                                                          'data-field': 'id_n_participantes'}),
            'maletin_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'block': forms.Select(attrs={'onchange': 'CargarInfo("block",this.value);', 'class': 'form-control', 'data-label': 'id_block_unitario'}),
            'block_unitario':  forms.NumberInput(attrs={'readonly': True,
                                                        'placeholder': "Costo unitario",
                                                        'class': 'text-currency textInput form-control valor-total',
                                                        'data-total': 'id_block_total',
                                                        'data-depend': 'True',
                                                        'data-field': 'id_n_participantes'}),
            'block_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'lapiz': forms.Select(attrs={'onchange': 'CargarInfo("lapiz",this.value);', 'class': 'form-control', 'data-label': 'id_lapiz_unitario'}),
            'lapiz_unitario': forms.NumberInput(attrs={'readonly': True,
                                                       'placeholder': "Costo unitario",
                                                       'class': 'text-currency textInput form-control valor-total',
                                                       'data-total': 'id_lapiz_total',
                                                       'data-depend': 'True',
                                                       'data-field': 'id_n_participantes'}),
            'lapiz_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'pluma': forms.Select(attrs={'onchange': 'CargarInfo("pluma",this.value);', 'class': 'form-control', 'data-label': 'id_pluma_unitario'}),
            'pluma_unitario': forms.NumberInput(attrs={'readonly': True,
                                                       'placeholder': "Costo unitario",
                                                       'class': 'text-currency textInput form-control valor-total',
                                                       'data-total': 'id_pluma_total',
                                                       'data-depend': 'True',
                                                       'data-field': 'id_n_participantes'}),
            'pluma_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'credencial_plastico': forms.Select(attrs={'onchange': 'CargarInfo("credencial_plastico",this.value);', 'class': 'form-control otros', 'data-label': 'id_credencial_plastico_unitario'}),
            'credencial_plastico_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                     'placeholder': "Costo unitario",
                                                                     'class': 'text-currency textInput form-control valor-total',
                                                                     'data-total': 'id_credencial_plastico_total',
                                                                     'data-depend': 'True',
                                                                     'data-field': 'id_n_participantes'}),
            'credencial_plastico_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'credencial_pvc': forms.Select(attrs={'onchange': 'CargarInfo("credencial_pvc",this.value);', 'class': 'form-control otros', 'data-label': 'id_credencial_pvc_unitario'}),
            'credencial_pvc_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                'placeholder': "Costo unitario",
                                                                'class': 'text-currency textInput form-control valor-total',
                                                                'data-total': 'id_credencial_pvc_total',
                                                                'data-depend': 'True',
                                                                'data-field': 'id_n_participantes'}),
            'credencial_pvc_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'pendrive': forms.Select(attrs={'onchange': 'CargarInfo("pendrive",this.value);', 'class': 'form-control', 'data-label': 'id_pendrive_unitario'}),
            'pendrive_unitario': forms.NumberInput(attrs={'readonly': True,
                                                          'placeholder': "Costo unitario",
                                                          'class': 'text-currency textInput form-control valor-total',
                                                          'data-total': 'id_pendrive_total',
                                                          'data-depend': 'True',
                                                          'data-field': 'id_n_participantes'}),
            'pendrive_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'otros_materiales': forms.Select(attrs={'onchange': 'CargarInfo("otros_materiales",this.value);', 'class': 'form-control otros', 'data-label': 'id_otros_materiales_unitario'}),
            'otros_materiales_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                  'placeholder': "Costo unitario",
                                                                  'class': 'text-currency textInput form-control valor-total',
                                                                  'data-total': 'id_otros_materiales_total',
                                                                  'data-depend': 'True',
                                                                  'data-field': 'id_n_participantes'}),
            'otros_materiales_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            "break_evento": forms.Select(attrs={'onchange': 'CargarInfo("break_evento",this.value);', 'class': 'form-control'}),
            'break_evento_dias': forms.NumberInput(attrs={'min': 0,
                                                          'placeholder': "# días",
                                                          'class': 'textInput form-control valor-total',
                                                          'data-total': 'break_participantes',
                                                          'data-depend': 'True',
                                                          'data-field': 'id_n_participantes'}),
            'break_evento_unitario': forms.NumberInput(attrs={'readonly': True,
                                                              'placeholder': "Costo Break por día",
                                                              'class': 'text-currency textInput form-control valor-total',
                                                              'data-total': 'id_break_evento_total',
                                                              'data-depend': 'True',
                                                              'data-field': 'break_participantes'}),
            'break_evento_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Break Total", 'class': 'egreso-variable text-currency textInput form-control'}),
            "almuerzo_evento": forms.Select(attrs={'onchange': 'CargarInfo("almuerzo_evento",this.value);', 'class': 'form-control'}),
            'almuerzo_evento_dias': forms.NumberInput(attrs={'min': 0,
                                                             'placeholder': "# días",
                                                             'class': 'textInput form-control valor-total',
                                                             "data-total": "almuerzo_participantes",
                                                             'data-depend': 'True',
                                                             'data-field': 'id_n_participantes'}),
            'almuerzo_evento_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                 'placeholder': "Costo Almuerzo por día",
                                                                 'class': 'text-currency textInput form-control valor-total',
                                                                 "data-total": "id_almuerzo_evento_total",
                                                                 'data-depend': 'True',
                                                                 'data-field': 'almuerzo_participantes'}),
            'almuerzo_evento_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Almuerzo Total", 'class': 'egreso-variable text-currency textInput form-control'}),
            'ceremonia': forms.Select(attrs={'onchange': 'CargarInfo("ceremonia",this.value);', 'class': 'form-control otros', 'data-label': 'id_ceremonia_unitario'}),
            'ceremonia_unitario': forms.NumberInput(attrs={'readonly': True,
                                                           'placeholder': "Costo unitario",
                                                           'class': 'text-currency textInput form-control valor-total',
                                                           'data-total': 'id_ceremonia_total',
                                                           'data-depend': 'True',
                                                           'data-field': 'ceremonia_participantes'}),
            'ceremonia_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'aportacion_espol_porcentaje': forms.NumberInput(attrs={'readonly': True, 'min': 0, 'max': 100.00,
                                                                    'placeholder': "aporte",
                                                                    'class': 'text-currency textInput form-control valor-porcentaje',
                                                                    'data-total': 'id_aportacion_espol_unitario',
                                                                    'data-depend': 'True',
                                                                    'data-field': 'id_ingreso_neto_individual'}),
            'aportacion_espol_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                  'placeholder': "Costo unitario",
                                                                  'class': 'text-currency textInput form-control valor-total',
                                                                  'data-total': 'id_aportacion_espol_total',
                                                                  'data-depend': 'True',
                                                                  'data-field': 'id_n_participantes'}),
            'aportacion_espol_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'aportacion_espoltech_porcentaje': forms.NumberInput(attrs={'readonly': True, 'min': 0, 'max': 100,
                                                                        'placeholder': "aporte",
                                                                        'class': 'text-currency textInput form-control valor-porcentaje',
                                                                        'data-total': 'id_aportacion_espoltech_unitario',
                                                                        'data-depend': 'True',
                                                                        'data-field': 'id_ingreso_neto_individual'}),
            'aportacion_espoltech_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                      'placeholder': "aporte",
                                                                      'class': 'text-currency textInput form-control valor-total',
                                                                      'data-total': 'id_aportacion_espoltech_total',
                                                                      'data-depend': 'True',
                                                                      'data-field': 'id_n_participantes'}),
            'aportacion_espoltech_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'aportacion_ministerio_porcentaje': forms.NumberInput(attrs={'readonly': True, 'min': 0, 'max': 100,
                                                                         'placeholder': "aporte",
                                                                         'class': 'text-currency textInput form-control valor-porcentaje',
                                                                         'data-total': 'id_aportacion_ministerio_unitario',
                                                                         'data-depend': 'True',
                                                                         'data-field': 'id_ingreso_neto_individual'}),
            'aportacion_ministerio_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                       'placeholder': "Costo unitario",
                                                                       'class': 'text-currency textInput form-control valor-total',
                                                                       'data-total': 'id_aportacion_ministerio_total',
                                                                       'data-depend': 'True',
                                                                       'data-field': 'id_n_participantes'}),
            'aportacion_ministerio_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'aportacion_facultad': forms.Select(attrs={'onchange': 'CargarInfo("aportacion_facultad_porcentaje",this.value);', 'class': 'form-control'}),
            'aportacion_facultad_porcentaje_unitario': forms.NumberInput(attrs={'readonly': True, 'min': 0, 'max': 100,
                                                                                'placeholder': "aporte",
                                                                                'class': 'text-currency textInput form-control valor-porcentaje',
                                                                                'data-total': 'id_aportacion_facultad_unitario',
                                                                                'data-depend': 'True',
                                                                                'data-field': 'id_ingreso_neto_individual'}),
            'aportacion_facultad_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                     'placeholder': "Costo unitario",
                                                                     'class': 'text-currency textInput form-control valor-total',
                                                                     'data-total': 'id_aportacion_facultad_total',
                                                                     'data-depend': 'True',
                                                                     'data-field': 'id_n_participantes'}),
            'aportacion_facultad_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'movilizacion_interna_unitario': forms.NumberInput(attrs={'placeholder': 'Costo unitario',
                                                                      'class': 'text-currency textInput form-control valor-total',
                                                                      'data-total': 'id_movilizacion_interna_total',
                                                                      'data-depend': 'True',
                                                                      'data-field': 'id_n_dias'}),
            'movilizacion_interna_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'cafeteria_limpieza': forms.Select(attrs={'onchange': 'CargarInfo("cafeteria_limpieza",this.value);', 'class': 'form-control'}),
            'cafeteria_limpieza_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                    'placeholder': 'Costo unitario',
                                                                    'class': 'text-currency textInput form-control valor-total',
                                                                    'data-total': 'id_cafeteria_limpieza_total',
                                                                    'data-depend': 'True',
                                                                    'data-field': 'n_dias_participantes'}),
            'cafeteria_limpieza_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'imprevisto_porcentaje': forms.NumberInput(attrs={'placeholder': 'imprevisto', 'min': 0.5, 'max': 5.0,
                                                              'class': 'text-currency textInput form-control valor-porcentaje',
                                                              'data-total': 'id_imprevisto_unitario',
                                                              'data-depend': 'True',
                                                              'data-field': 'id_ingreso_neto_individual'}),
            'imprevisto_unitario': forms.NumberInput(attrs={'readonly': True,
                                                            'placeholder': 'Costo unitario',
                                                            'class': 'text-currency textInput form-control valor-total',
                                                            'data-total': 'id_imprevisto_total',
                                                            'data-depend': 'True',
                                                            'data-field': 'id_n_participantes'}),
            'imprevisto_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'total_egresos_variables': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Total egresos variables', 'class': 'form-control textInput text-currency border border-success'}),
            'total_egresos': forms.NumberInput(attrs={'readonly': True,
                                                      'placeholder': 'Total egresos',
                                                      'class': 'form-control textInput text-currency border border-success',
                                                      'data-total': 'id_egreso_variable_unit',
                                                      'data-depend': 'True',
                                                      'data-field': 'id_n_participantes'}),

            'egreso_variable_unit': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Egreso variable unit', 'class': 'form-control textInput text-currency punto'}),
            'margen_contribucion': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Contribución', 'class': 'form-control textInput text-currency'}),
            'utilidad': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Utilidad', 'class': 'form-control textInput text-currency'}),
            'punto_equilibrio': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Equilibrio', 'class': 'form-control textInput text-currency'}),
            'n_cursos': forms.NumberInput(attrs={'class': 'form-control textInput text-currency valor-total',
                                                 'data-total': 'id_participacion_total',
                                                 'data-depend': 'True',
                                                 'data-field': 'resumen_aporte_facultad'}),
            'participacion_total': forms.NumberInput(attrs={'readonly': True, 'class': 'form-control textInput text-currency'}),
            'pago_docente_total': forms.NumberInput(attrs={'readonly': True, 'class': 'form-control textInput text-currency'}),
            "motivo_anular": forms.Textarea(attrs={"class": "form-control", "rows": 2}),
            "observaciones": forms.Textarea(attrs={"class": "form-control", "rows": 2}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class PresupuestoEventoFormUpdate(forms.ModelForm):
    # estado=
    class Meta:
        model = PresupuestoEvento
        fields = "__all__"
        labels = {
            'estado': '',
            'codigo': '',
            'fecha': '',
            'ingreso_individual_sin_desc': '',
            'ingreso_total_sin_desc': '',
            'descuento_maximo': '',
            'descuento_individual': '',
            'descuento_total': '',

            'ingreso_neto_individual': '',
            'ingreso_neto_total': '',

            'porcentaje_honorario_instructor': '',
            'honorario_total_evento': '',

            'impuesto_select': '',
            'impuesto_unitario': '',
            'impuesto_total': '',

            'pasaje_instructor': '',
            'pasaje_instructor_unitario': '',
            'pasaje_instructor_total': '',

            'hospedaje_alimentacion_instructor': '',
            'hospedaje_alimentacion_instructor_dias': '',
            'hospedaje_alimentacion_instructor_n': '',
            'hospedaje_alimentacion_instructor_unitario': '',
            'hospedaje_alimentacion_instructor_total': '',

            'break_instructor': '',
            'break_instructor_dias': '',
            'break_instructor_n': '',
            'break_instructor_unitario': '',
            'break_instructor_total': '',

            'almuerzo_instructor': '',
            'almuerzo_instructor_dias': '',
            'almuerzo_instructor_n': '',
            'almuerzo_instructor_unitario': '',
            'almuerzo_instructor_total': '',

            'pasaje_personal': '',
            'pasaje_personal_dias': '',
            'pasaje_personal_unitario': '',
            'pasaje_personal_total': '',

            'hospedaje_alimentacion_personal': '',
            'hospedaje_alimentacion_personal_dias': '',
            'hospedaje_alimentacion_personal_unitario': '',
            'hospedaje_alimentacion_personal_total': '',

            'movilizacion_personal_dias': '',
            'movilizacion_personal_unitario': '',
            'movilizacion_personal_total': '',

            'instalaciones': '',
            'instalaciones_unitario': '',
            'instalaciones_total': '',

            'publicidad_unitario': '',
            'publicidad_total': '',

            'personal_evento_unitario': '',
            'personal_evento_total': '',

            'prospecto_evento': '',
            'prospecto_evento_unitario': '',
            'prospecto_evento_total': '',

            'total_egresos_fijos': '',

            # Material del evento
            'certificados': '',
            'certificados_unitario': '',
            'certificados_total': '',

            'carpeta': '',
            'carpeta_unitario': '',
            'carpeta_total': '',

            'maletin': '',
            'maletin_unitario': '',
            'maletin_total': '',

            'block': '',
            'block_unitario': '',
            'block_total': '',

            'lapiz': '',
            'lapiz_unitario': '',
            'lapiz_total': '',

            'pluma': '',
            'pluma_unitario': '',
            'pluma_total': '',

            'credencial_plastico': '',
            'credencial_plastico_unitario': '',
            'credencial_plastico_total': '',

            'credencial_pvc': '',
            'credencial_pvc_unitario': '',
            'credencial_pvc_total': '',

            'pendrive': '',
            'pendrive_unitario': '',
            'pendrive_total': '',

            'otros_materiales': '',
            'otros_materiales_unitario': '',
            'otros_materiales_total': '',

            'break_evento': '',
            'break_evento_dias': '',
            'break_evento_unitario': '',
            'break_evento_total': '',

            'almuerzo_evento': '',
            'almuerzo_evento_dias': '',
            'almuerzo_evento_unitario': '',
            'almuerzo_evento_total': '',

            'ceremonia': '',
            'ceremonia_unitario': '',
            'ceremonia_total': '',

            'aportacion_espol_porcentaje': '',
            'aportacion_espol_unitario': '',
            'aportacion_espol_total': '',

            'aportacion_espoltech_porcentaje': '',
            'aportacion_espoltech_unitario': '',
            'aportacion_espoltech_total': '',

            'aportacion_ministerio_porcentaje': '',
            'aportacion_ministerio_unitario': '',
            'aportacion_ministerio_total': '',

            'aportacion_facultad': '',
            'aportacion_facultad_porcentaje_unitario': '',
            'aportacion_facultad_unitario': '',
            'aportacion_facultad_total': '',

            'movilizacion_interna_unitario': '',
            'movilizacion_interna_total': '',

            'cafeteria_limpieza': '',
            'cafeteria_limpieza_unitario': '',
            'cafeteria_limpieza_total': '',

            'imprevisto_porcentaje': '',
            'imprevisto_unitario': '',
            'imprevisto_total': '',

            'total_egresos_variables': '',
            'total_egresos': '',

            'egreso_variable_unit': '',
            'utilidad': '',
            'margen_contribucion': '',
            'punto_equilibrio': '',

            'n_cursos': '',
            'participacion_total': '',

            'pago_docente_total': '',
        }
        widgets = {
            'empresa': forms.Select(attrs={'disabled': True, 'class': 'form-control select2'}),
            'centro_costos': forms.Select(attrs={'disabled': True, 'class': 'form-control textInput'}),
            'fecha': forms.DateInput(attrs={'type': 'date', 'readonly': True, 'class': 'form-control'}),
            "pasaje_instructor": forms.Select(attrs={'onchange': 'CargarInfo("pasaje_instructor",this.value);', 'class': 'form-control'}),
            "estado": forms.TextInput(attrs={'class': 'form-control', 'readonly': True, 'placeholder': 'Estado'}),
            "codigo": forms.TextInput(attrs={'class': 'form-control', 'readonly': True, 'placeholder': 'Código'}),
            "costo_hora_instructores": forms.HiddenInput(),
            "costo_instructores": forms.TextInput(attrs={'readonly': True, 'class': 'text-currency textInput form-control'}),
            "hora_inicio": forms.TimeInput(attrs={'type': 'time', 'readonly':True}),
            "hora_fin": forms.TimeInput(attrs={'type': 'time', 'readonly':True}),
            "n_horas": forms.NumberInput(attrs={'min': 0, 'readonly':True}),
            "n_dias": forms.NumberInput(attrs={'min': 0, 'readonly':True}),
            "n_participantes": forms.NumberInput(attrs={'min': 0, 'readonly':True}),
            'ingreso_individual_sin_desc': forms.NumberInput(attrs={'placeholder': "Ingreso sin descuento individual", 'class': 'text-currency textInput form-control', 'readonly':True}),
            'descuento_maximo': forms.NumberInput(attrs={'placeholder': "Descuento máximo", 'step': 1, 'class': 'text-currency textInput form-control', 'readonly':True}),
            'descuento_individual': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Descuento individual", 'class': 'text-currency textInput form-control'}),
            "ingreso_total_sin_desc": forms.NumberInput(attrs={'readonly': True, 'placeholder': "Ingreso sin descuento total", 'class': 'text-currency textInput form-control'}),
            "descuento_total": forms.NumberInput(attrs={'readonly': True, 'placeholder': "Descuento max total", 'class': 'text-currency textInput form-control'}),
            'ingreso_neto_individual': forms.NumberInput(attrs={'readonly': True, 'class': 'border border-success text-currency textInput form-control', 'placeholder': "Ingreso neto individual"}),
            'ingreso_neto_total': forms.NumberInput(attrs={'readonly': True, 'class': 'border border-success text-currency textInput form-control', 'placeholder': "Ingreso neto total"}),
            'porcentaje_honorario_instructor': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Honorario', 'class': 'text-currency textInput form-control'}),
            'honorario_total_evento': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Honorario total del evento", 'class': 'egreso-fijo text-currency textInput form-control'}),

            'impuesto_unitario': forms.HiddenInput(),
            'impuesto_total': forms.HiddenInput(),
            'impuesto_select': forms.HiddenInput(),
            'pasaje_instructor':forms.Select(attrs={'disabled':True}),
            'pasaje_instructor_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                   'placeholder': "Costo Pasaje",
                                                                   'class': 'text-currency textInput form-control valor-total',
                                                                   'data-total': 'id_pasaje_instructor_total',
                                                                   'data-depend': 'False',
                                                                   'data-field': ''}),
            'pasaje_instructor_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Pasaje Total", 'class': 'egreso-fijo text-currency textInput form-control'}),
            "hospedaje_alimentacion_instructor": forms.Select(attrs={'disabled':True, 'class': 'form-control'}),
            'hospedaje_alimentacion_instructor_n': forms.NumberInput(attrs={'min': 0,'readonly':True,
                                                                            'placeholder': '# instructores',
                                                                            'class': 'textInput form-control valor-total',
                                                                            "data-total": "hospedaje_alimentacion_instructor_r",
                                                                            'data-depend': 'True',
                                                                            'data-field': 'id_hospedaje_alimentacion_instructor_dias'}),
            'hospedaje_alimentacion_instructor_dias': forms.NumberInput(attrs={'min': 0,'readonly':True,
                                                                               'placeholder': "# días",
                                                                               'class': 'textInput form-control valor-total',
                                                                               'data-total': 'hospedaje_alimentacion_instructor_r',
                                                                               'data-depend': 'True',
                                                                               'data-field': 'id_hospedaje_alimentacion_instructor_n'}),
            'hospedaje_alimentacion_instructor_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                                   'placeholder': "Costo HyA por día",
                                                                                   'class': 'text-currency textInput form-control valor-total',
                                                                                   'data-total': 'id_hospedaje_alimentacion_instructor_total',
                                                                                   'data-depend': 'True',
                                                                                   'data-field': 'hospedaje_alimentacion_instructor_r'}),
            'hospedaje_alimentacion_instructor_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo HyA Total", 'class': 'egreso-fijo text-currency textInput form-control'}),
            "break_instructor": forms.Select(attrs={'disabled':True, 'class': 'form-control'}),
            'break_instructor_n': forms.NumberInput(attrs={'min': 0,'readonly':True,
                                                           'placeholder': '# instructores',
                                                           'class': 'textInput form-control valor-total',
                                                           "data-total": "break_instructor_r",
                                                           'data-depend': 'True',
                                                           'data-field': 'id_break_instructor_dias'}),
            'break_instructor_dias': forms.NumberInput(attrs={'min': 0,'readonly':True,
                                                              'placeholder': "# días",
                                                              'class': 'textInput form-control valor-total',
                                                              'data-total': 'break_instructor_r',
                                                              'data-depend': 'True',
                                                              'data-field': 'id_break_instructor_n'}),
            'break_instructor_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                  'placeholder': "Costo Break por día",
                                                                  'class': 'text-currency textInput form-control valor-total',
                                                                  'data-total': 'id_break_instructor_total',
                                                                  'data-depend': 'True',
                                                                  'data-field': 'break_instructor_r'}),
            'break_instructor_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Break Total", 'class': 'egreso-fijo text-currency textInput form-control'}),
            "almuerzo_instructor": forms.Select(attrs={'disabled':True, 'class': 'form-control'}),
            'almuerzo_instructor_n': forms.NumberInput(attrs={'min': 0,'readonly':True,
                                                              'placeholder': '# instructores',
                                                              'class': 'textInput form-control valor-total',
                                                              "data-total": "almuerzo_instructor_r",
                                                              'data-depend': 'True',
                                                              'data-field': 'id_almuerzo_instructor_dias'}),
            'almuerzo_instructor_dias': forms.NumberInput(attrs={'min': 0,'readonly':True,
                                                                 'placeholder': "# días",
                                                                 'class': 'textInput form-control valor-total',
                                                                 "data-total": "almuerzo_instructor_r",
                                                                 'data-depend': 'True',
                                                                 'data-field': 'id_almuerzo_instructor_n'}),
            'almuerzo_instructor_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                     'placeholder': "Costo Almuerzo por día",
                                                                     'class': 'text-currency textInput form-control valor-total',
                                                                     "data-total": "id_almuerzo_instructor_total",
                                                                     'data-depend': 'True',
                                                                     'data-field': 'almuerzo_instructor_r'}),
            'almuerzo_instructor_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Almuerzo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            "pasaje_personal": forms.Select(attrs={'disabled':True, 'class': 'form-control'}),
            'pasaje_personal_dias': forms.NumberInput(attrs={'min': 0,'readonly': True,
                                                             'placeholder': "# días",
                                                             'class': 'textInput form-control valor-total',
                                                             'data-total': 'id_pasaje_personal_total',
                                                             'data-depend': 'True',
                                                             'data-field': 'id_pasaje_personal_unitario'}),
            'pasaje_personal_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                 'placeholder': "Costo HyA por día",
                                                                 'class': 'text-currency textInput form-control valor-total',
                                                                 'data-total': 'id_pasaje_personal_total',
                                                                 'data-depend': 'True',
                                                                 'data-field': 'id_pasaje_personal_dias'}),
            'pasaje_personal_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo HyA Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            "hospedaje_alimentacion_personal": forms.Select(attrs={'disabled':True, 'class': 'form-control'}),
            'hospedaje_alimentacion_personal_dias': forms.NumberInput(attrs={'min': 0,'readonly': True,
                                                                             'placeholder': "# días",
                                                                             'class': 'textInput form-control valor-total',
                                                                             'data-total': 'id_hospedaje_alimentacion_personal_total',
                                                                             'data-depend': 'True',
                                                                             'data-field': 'id_hospedaje_alimentacion_personal_unitario'
                                                                             }),
            'hospedaje_alimentacion_personal_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                                 'placeholder': "Costo HyA por día",
                                                                                 'class': 'text-currency textInput form-control valor-total',
                                                                                 'data-total': 'id_hospedaje_alimentacion_personal_total',
                                                                                 'data-depend': 'True',
                                                                                 'data-field': 'id_hospedaje_alimentacion_personal_dias'
                                                                                 }),
            'hospedaje_alimentacion_personal_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo HyA Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            'movilizacion_personal_dias': forms.NumberInput(attrs={'min': 0,'readonly': True,
                                                                   'placeholder': "# días",
                                                                   'class': 'textInput form-control valor-total',
                                                                   'data-total': 'id_movilizacion_personal_total',
                                                                   'data-depend': 'True',
                                                                   'data-field': 'id_movilizacion_personal_unitario'}),
            'movilizacion_personal_unitario': forms.NumberInput(attrs={'placeholder': "Costo HyA por día",'readonly': True,
                                                                       'class': 'text-currency textInput form-control valor-total',
                                                                       'data-total': 'id_movilizacion_personal_total',
                                                                       'data-depend': 'True',
                                                                       'data-field': 'id_movilizacion_personal_dias'}),
            'movilizacion_personal_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo HyA Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            "instalaciones": forms.Select(attrs={'disabled':True, 'class': 'form-control'}),
            'instalaciones_unitario': forms.NumberInput(attrs={'readonly': True,
                                                               'placeholder': "Costo por día",
                                                               'class': 'text-currency textInput form-control valor-total',
                                                               'data-total': 'id_instalaciones_total',
                                                               'data-depend': 'True',
                                                               'data-field': 'id_n_horas'
                                                               }),
            'instalaciones_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            'publicidad_unitario': forms.NumberInput(attrs={'placeholder': "Costo por día",'readonly': True,
                                                            'class': 'text-currency textInput form-control valor-total',
                                                            'data-total': 'id_publicidad_total',
                                                            'data-depend': 'False',
                                                            'data-field': ''
                                                            }),
            'publicidad_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            'publicidad_evento_unitario': forms.NumberInput(attrs={'placeholder': "Costo por día",'readonly': True,
                                                                   'class': 'text-currency textInput form-control valor-total',
                                                                   'data-total': 'id_publicidad_evento_total',
                                                                   'data-depend': 'True',
                                                                   'data-field': 'id_n_participantes'
                                                                   }),
            'publicidad_evento_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            'personal_evento_unitario': forms.NumberInput(attrs={'placeholder': "Costo por día",'readonly':True,
                                                                 'class': 'text-currency textInput form-control valor-total',
                                                                 'data-total': 'id_personal_evento_total',
                                                                 'data-depend': 'True',
                                                                 'data-field': 'id_n_horas'
                                                                 }),
            'personal_evento_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),

            "prospecto_evento": forms.Select(attrs={'disabled': True, 'class': 'form-control'}),
            'prospecto_evento_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                  'placeholder': "Costo por día",
                                                                  'class': 'text-currency textInput form-control valor-total',
                                                                  'data-total': 'id_prospecto_evento_total',
                                                                  'data-depend': 'False',
                                                                  'data-field': ''
                                                                  }),
            'prospecto_evento_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Total", 'class': 'egreso-fijo text-currency textInput form-control'}),
            'total_egresos_fijos': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Total egresos fijos', 'class': 'punto form-control textInput text-currency border border-success'}),

            'certificados': forms.Select(attrs={'disabled':True, 'class': 'form-control', 'data-label': 'id_certificados_unitario'}),
            'certificados_unitario': forms.NumberInput(attrs={'readonly': True,
                                                              'placeholder': "Costo unitario",
                                                              'class': 'text-currency textInput form-control valor-total',
                                                              'data-total': 'id_certificados_total',
                                                              'data-depend': 'True',
                                                              'data-field': 'id_n_participantes'}),
            'certificados_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'carpeta': forms.Select(attrs={'disabled':True, 'class': 'form-control', 'data-label': 'id_carpeta_unitario'}),
            'carpeta_unitario': forms.NumberInput(attrs={'readonly': True,
                                                         'placeholder': "Costo unitario",
                                                         'class': 'text-currency textInput form-control valor-total',
                                                         'data-total': 'id_carpeta_total',
                                                         'data-depend': 'True',
                                                         'data-field': 'id_n_participantes'}),
            'carpeta_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'maletin': forms.Select(attrs={'disabled':True, 'class': 'form-control otros', 'data-label': 'id_maletin_unitario'}),
            'maletin_unitario':  forms.NumberInput(attrs={'readonly': True,
                                                          'placeholder': "Costo unitario",
                                                          'class': 'text-currency textInput form-control valor-total',
                                                          'data-total': 'id_maletin_total',
                                                          'data-depend': 'True',
                                                          'data-field': 'id_n_participantes'}),
            'maletin_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'block': forms.Select(attrs={'disabled':True, 'class': 'form-control', 'data-label': 'id_block_unitario'}),
            'block_unitario':  forms.NumberInput(attrs={'readonly': True,
                                                        'placeholder': "Costo unitario",
                                                        'class': 'text-currency textInput form-control valor-total',
                                                        'data-total': 'id_block_total',
                                                        'data-depend': 'True',
                                                        'data-field': 'id_n_participantes'}),
            'block_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'lapiz': forms.Select(attrs={'disabled':True, 'class': 'form-control', 'data-label': 'id_lapiz_unitario'}),
            'lapiz_unitario': forms.NumberInput(attrs={'readonly': True,
                                                       'placeholder': "Costo unitario",
                                                       'class': 'text-currency textInput form-control valor-total',
                                                       'data-total': 'id_lapiz_total',
                                                       'data-depend': 'True',
                                                       'data-field': 'id_n_participantes'}),
            'lapiz_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'pluma': forms.Select(attrs={'disabled':True, 'class': 'form-control', 'data-label': 'id_pluma_unitario'}),
            'pluma_unitario': forms.NumberInput(attrs={'readonly': True,
                                                       'placeholder': "Costo unitario",
                                                       'class': 'text-currency textInput form-control valor-total',
                                                       'data-total': 'id_pluma_total',
                                                       'data-depend': 'True',
                                                       'data-field': 'id_n_participantes'}),
            'pluma_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'credencial_plastico': forms.Select(attrs={'disabled':True,'class': 'form-control otros', 'data-label': 'id_credencial_plastico_unitario'}),
            'credencial_plastico_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                     'placeholder': "Costo unitario",
                                                                     'class': 'text-currency textInput form-control valor-total',
                                                                     'data-total': 'id_credencial_plastico_total',
                                                                     'data-depend': 'True',
                                                                     'data-field': 'id_n_participantes'}),
            'credencial_plastico_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'credencial_pvc': forms.Select(attrs={'disabled':True, 'class': 'form-control otros', 'data-label': 'id_credencial_pvc_unitario'}),
            'credencial_pvc_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                'placeholder': "Costo unitario",
                                                                'class': 'text-currency textInput form-control valor-total',
                                                                'data-total': 'id_credencial_pvc_total',
                                                                'data-depend': 'True',
                                                                'data-field': 'id_n_participantes'}),
            'credencial_pvc_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'pendrive': forms.Select(attrs={'disabled':True, 'class': 'form-control', 'data-label': 'id_pendrive_unitario'}),
            'pendrive_unitario': forms.NumberInput(attrs={'readonly': True,
                                                          'placeholder': "Costo unitario",
                                                          'class': 'text-currency textInput form-control valor-total',
                                                          'data-total': 'id_pendrive_total',
                                                          'data-depend': 'True',
                                                          'data-field': 'id_n_participantes'}),
            'pendrive_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'otros_materiales': forms.Select(attrs={'disabled':True, 'class': 'form-control otros', 'data-label': 'id_otros_materiales_unitario'}),
            'otros_materiales_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                  'placeholder': "Costo unitario",
                                                                  'class': 'text-currency textInput form-control valor-total',
                                                                  'data-total': 'id_otros_materiales_total',
                                                                  'data-depend': 'True',
                                                                  'data-field': 'id_n_participantes'}),
            'otros_materiales_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            "break_evento": forms.Select(attrs={'disabled':True, 'class': 'form-control'}),
            'break_evento_dias': forms.NumberInput(attrs={'min': 0,'readonly': True,
                                                          'placeholder': "# días",
                                                          'class': 'textInput form-control valor-total',
                                                          'data-total': 'break_participantes',
                                                          'data-depend': 'True',
                                                          'data-field': 'id_n_participantes'}),
            'break_evento_unitario': forms.NumberInput(attrs={'readonly': True,
                                                              'placeholder': "Costo Break por día",
                                                              'class': 'text-currency textInput form-control valor-total',
                                                              'data-total': 'id_break_evento_total',
                                                              'data-depend': 'True',
                                                              'data-field': 'break_participantes'}),
            'break_evento_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Break Total", 'class': 'egreso-variable text-currency textInput form-control'}),
            "almuerzo_evento": forms.Select(attrs={'disabled':True, 'class': 'form-control'}),
            'almuerzo_evento_dias': forms.NumberInput(attrs={'min': 0,'readonly':True, 
                                                             'placeholder': "# días",
                                                             'class': 'textInput form-control valor-total',
                                                             "data-total": "almuerzo_participantes",
                                                             'data-depend': 'True',
                                                             'data-field': 'id_n_participantes'}),
            'almuerzo_evento_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                 'placeholder': "Costo Almuerzo por día",
                                                                 'class': 'text-currency textInput form-control valor-total',
                                                                 "data-total": "id_almuerzo_evento_total",
                                                                 'data-depend': 'True',
                                                                 'data-field': 'almuerzo_participantes'}),
            'almuerzo_evento_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': "Costo Almuerzo Total", 'class': 'egreso-variable text-currency textInput form-control'}),
            'ceremonia': forms.Select(attrs={'disabled':True,  'class': 'form-control otros', 'data-label': 'id_ceremonia_unitario'}),
            'ceremonia_unitario': forms.NumberInput(attrs={'readonly': True,
                                                           'placeholder': "Costo unitario",
                                                           'class': 'text-currency textInput form-control valor-total',
                                                           'data-total': 'id_ceremonia_total',
                                                           'data-depend': 'True',
                                                           'data-field': 'ceremonia_participantes'}),
            'ceremonia_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'aportacion_espol_porcentaje': forms.NumberInput(attrs={'readonly': True, 'min': 0, 'max': 100.00,
                                                                    'placeholder': "aporte",
                                                                    'class': 'text-currency textInput form-control valor-porcentaje',
                                                                    'data-total': 'id_aportacion_espol_unitario',
                                                                    'data-depend': 'True',
                                                                    'data-field': 'id_ingreso_neto_individual'}),
            'aportacion_espol_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                  'placeholder': "Costo unitario",
                                                                  'class': 'text-currency textInput form-control valor-total',
                                                                  'data-total': 'id_aportacion_espol_total',
                                                                  'data-depend': 'True',
                                                                  'data-field': 'id_n_participantes'}),
            'aportacion_espol_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'aportacion_espoltech_porcentaje': forms.NumberInput(attrs={'readonly': True, 'min': 0, 'max': 100,
                                                                        'placeholder': "aporte",
                                                                        'class': 'text-currency textInput form-control valor-porcentaje',
                                                                        'data-total': 'id_aportacion_espoltech_unitario',
                                                                        'data-depend': 'True',
                                                                        'data-field': 'id_ingreso_neto_individual'}),
            'aportacion_espoltech_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                      'placeholder': "aporte",
                                                                      'class': 'text-currency textInput form-control valor-total',
                                                                      'data-total': 'id_aportacion_espoltech_total',
                                                                      'data-depend': 'True',
                                                                      'data-field': 'id_n_participantes'}),
            'aportacion_espoltech_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'aportacion_ministerio_porcentaje': forms.NumberInput(attrs={'readonly': True, 'min': 0, 'max': 100,
                                                                         'placeholder': "aporte",
                                                                         'class': 'text-currency textInput form-control valor-porcentaje',
                                                                         'data-total': 'id_aportacion_ministerio_unitario',
                                                                         'data-depend': 'True',
                                                                         'data-field': 'id_ingreso_neto_individual'}),
            'aportacion_ministerio_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                       'placeholder': "Costo unitario",
                                                                       'class': 'text-currency textInput form-control valor-total',
                                                                       'data-total': 'id_aportacion_ministerio_total',
                                                                       'data-depend': 'True',
                                                                       'data-field': 'id_n_participantes'}),
            'aportacion_ministerio_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'aportacion_facultad': forms.Select(attrs={'disabled':True, 'class': 'form-control'}),
            'aportacion_facultad_porcentaje_unitario': forms.NumberInput(attrs={'readonly': True, 'min': 0, 'max': 100,
                                                                                'placeholder': "aporte",
                                                                                'class': 'text-currency textInput form-control valor-porcentaje',
                                                                                'data-total': 'id_aportacion_facultad_unitario',
                                                                                'data-depend': 'True',
                                                                                'data-field': 'id_ingreso_neto_individual'}),
            'aportacion_facultad_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                     'placeholder': "Costo unitario",
                                                                     'class': 'text-currency textInput form-control valor-total',
                                                                     'data-total': 'id_aportacion_facultad_total',
                                                                     'data-depend': 'True',
                                                                     'data-field': 'id_n_participantes'}),
            'aportacion_facultad_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'movilizacion_interna_unitario': forms.NumberInput(attrs={'placeholder': 'Costo unitario','readonly':True, 
                                                                      'class': 'text-currency textInput form-control valor-total',
                                                                      'data-total': 'id_movilizacion_interna_total',
                                                                      'data-depend': 'True',
                                                                      'data-field': 'id_n_dias'}),
            'movilizacion_interna_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),

            'cafeteria_limpieza': forms.Select(attrs={'disabled':True,  'class': 'form-control'}),
            'cafeteria_limpieza_unitario': forms.NumberInput(attrs={'readonly': True,
                                                                    'placeholder': 'Costo unitario',
                                                                    'class': 'text-currency textInput form-control valor-total',
                                                                    'data-total': 'id_cafeteria_limpieza_total',
                                                                    'data-depend': 'True',
                                                                    'data-field': 'n_dias_participantes'}),
            'cafeteria_limpieza_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'imprevisto_porcentaje': forms.NumberInput(attrs={'placeholder': 'imprevisto', 'min': 0.5, 'max': 5.0,'readonly':True, 
                                                              'class': 'text-currency textInput form-control valor-porcentaje',
                                                              'data-total': 'id_imprevisto_unitario',
                                                              'data-depend': 'True',
                                                              'data-field': 'id_ingreso_neto_individual'}),
            'imprevisto_unitario': forms.NumberInput(attrs={'readonly': True,
                                                            'placeholder': 'Costo unitario',
                                                            'class': 'text-currency textInput form-control valor-total',
                                                            'data-total': 'id_imprevisto_total',
                                                            'data-depend': 'True',
                                                            'data-field': 'id_n_participantes'}),
            'imprevisto_total': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Costo Total', 'class': 'egreso-variable text-currency textInput form-control'}),
            'total_egresos_variables': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Total egresos variables', 'class': 'form-control textInput text-currency border border-success'}),
            'total_egresos': forms.NumberInput(attrs={'readonly': True,
                                                      'placeholder': 'Total egresos',
                                                      'class': 'form-control textInput text-currency border border-success',
                                                      'data-total': 'id_egreso_variable_unit',
                                                      'data-depend': 'True',
                                                      'data-field': 'id_n_participantes'}),

            'egreso_variable_unit': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Egreso variable unit', 'class': 'form-control textInput text-currency punto'}),
            'margen_contribucion': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Contribución', 'class': 'form-control textInput text-currency'}),
            'utilidad': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Utilidad', 'class': 'form-control textInput text-currency'}),
            'punto_equilibrio': forms.NumberInput(attrs={'readonly': True, 'placeholder': 'Equilibrio', 'class': 'form-control textInput text-currency'}),
            'n_cursos': forms.NumberInput(attrs={'class': 'form-control textInput text-currency valor-total','readonly':True, 
                                                 'data-total': 'id_participacion_total',
                                                 'data-depend': 'True',
                                                 'data-field': 'resumen_aporte_facultad'}),
            'participacion_total': forms.NumberInput(attrs={'readonly': True, 'class': 'form-control textInput text-currency'}),
            'pago_docente_total': forms.NumberInput(attrs={'readonly': True, 'class': 'form-control textInput text-currency'}),
            "motivo_anular": forms.Textarea(attrs={'readonly':True,"class": "form-control", "rows": 2}),
            "observaciones": forms.Textarea(attrs={'readonly':True,"class": "form-control", "rows": 2}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


# class PresupuestoEventoFilter(django_filters.FilterSet):
# 	fecha = django_filters.DateFilter(
#         widget=forms.DateInput(
#             attrs={
#                 'id': 'datepicker',
#                 'type': 'date'
#             }
#         ))

# 	estado = django_filters.ChoiceFilter(
# 		#lookup_expr='isnull',
# 		null_label="Pendiente",
# 		empty_label="-------",
# 		#null_value="null",

# 		choices=TRUE_FALSE_CHOICES
# 		)
# 	#non_estado = django_filters.BooleanFilter(field_name='estado', lookup_expr='isnull')

# 	class Meta:
# 		model = PresupuestoEvento
# 		fields = ["nombre","codigo","aula","modalidad","empresa","nombre_instructor",
# 		"fecha","horario","n_horas","costo_hora_instructor","n_dias",
# 		"n_participantes","estado"]

# 	def __init__(self, *args, **kwargs):
# 		super().__init__(*args, **kwargs)
